name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
      id-token: write
    runs-on: windows-latest
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true # Setze die Variable global für den Job
    steps:
      - uses: actions/checkout@v2
      - name: Checkout private repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/Mehjung/paisy2pdf_lib_rs.git
          token: ${{ secrets.GH_PAT }}
          path: "private-repo"
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: "npm"
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: install frontend dependencies
        run: npm install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
