name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true #
    steps:
      - uses: actions/checkout@v4
      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: Mehjung/paisy2pdf_lib_rs.git
          token: ${{ secrets.GH_PAT }}
          path: "private-repo"
          ref: "main"
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: yarn install

      - name: Build and release Tauri app
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: "private-repo" # Adjust the path if your Tauri project is located elsewhere
          distPath: "private-repo/dist" # Path to the distributable folder containing your index.html and JS/CSS
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          includeUpdaterJson: true # Important for Tauri updater
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
