name: Update Installer Link in HTML

on:
  push:
    branches:
      - gh-pages

jobs:
  update-html:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find Latest Version
        run: |
          $versions = Get-ChildItem -Path .\releases\download\ -Directory | ForEach-Object { $_.Name }

          foreach ($version in $versions) {
            echo $version
            if ([Version]$version -gt $latestVersion) {
              $latestVersion = $version
            }
          }
          echo "Latest version is $latestVersion"
          echo "VERSION=$latestVersion" >> $GITHUB_ENV

      - name: Update Index HTML
        run: |
          $latestVersion = $env:VERSION
          $latestFile = (Get-ChildItem -Path ".\releases\download\$latestVersion" -Filter "*.exe").Name
          echo "Latest file is $latestFile"
          $latestPath = "https://mehjung.github.io/paisy2pdf/releases/download/$latestVersion/$latestFile"
          echo "Latest path is $latestPath"
          (Get-Content -Path index.html) -replace 'href=".*?"', "href=`"$latestPath`"" | Set-Content -Path index.html

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Update index.html mit dem neuesten Installer-Link"
          git push
